# (bố cục, nội dung, tên gốc, chủ đề)
# Câu Kinh Thánh dùng bản King James (public domain).
PHRASES = [
    # --- Christian ---
    ('verse', ('Be Still', 'and know', 'Be still, and know that I am God.', 'Psalm 46:10'), 'Be Still and Know Psalm 46:10', 'Christian'),
    ('verse', ('Faith', 'over fear', 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', '2 Timothy 1:7'), 'Faith Over Fear 2 Timothy 1:7', 'Christian'),
    ('verse', ('Blessed', 'and grateful', 'O give thanks unto the Lord; for he is good: for his mercy endureth for ever.', 'Psalm 136:1'), 'Blessed and Grateful Psalm 136:1', 'Christian'),
    ('verse', ('Walk by Faith', None, 'For we walk by faith, not by sight.', '2 Corinthians 5:7'), 'Walk by Faith 2 Corinthians 5:7', 'Christian'),
    ('verse', ('Grace', 'upon grace', 'For by grace are ye saved through faith.', 'Ephesians 2:8'), 'Saved by Grace Ephesians 2:8', 'Christian'),
    ('verse', ('Strength', 'in Christ', 'I can do all things through Christ which strengtheneth me.', 'Philippians 4:13'), 'All Things Through Christ Philippians 4:13', 'Christian'),
    ('verse', ('Shepherd', 'I shall not want', 'The Lord is my shepherd; I shall not want.', 'Psalm 23:1'), 'The Lord Is My Shepherd Psalm 23', 'Christian'),
    ('verse', ('Love', 'never faileth', 'Charity never faileth.', '1 Corinthians 13:8'), 'Love Never Fails 1 Corinthians 13', 'Christian'),
    ('verse', ('Joy', 'in the morning', 'Weeping may endure for a night, but joy cometh in the morning.', 'Psalm 30:5'), 'Joy Comes in the Morning Psalm 30:5', 'Christian'),
    ('verse', ('Light', 'of the world', 'Ye are the light of the world.', 'Matthew 5:14'), 'Light of the World Matthew 5:14', 'Christian'),
    ('verse', ('Hope', 'anchors the soul', 'Which hope we have as an anchor of the soul, both sure and stedfast.', 'Hebrews 6:19'), 'Hope Anchors the Soul Hebrews 6:19', 'Christian'),
    ('verse', ('Rejoice', 'always', 'Rejoice in the Lord alway: and again I say, Rejoice.', 'Philippians 4:4'), 'Rejoice Always Philippians 4:4', 'Christian'),
    ('verse', ('Trust', 'in the Lord', 'Trust in the Lord with all thine heart; and lean not unto thine own understanding.', 'Proverbs 3:5'), 'Trust in the Lord Proverbs 3:5', 'Christian'),
    ('verse', ('Wings', 'like eagles', 'They shall mount up with wings as eagles; they shall run, and not be weary.', 'Isaiah 40:31'), 'Wings Like Eagles Isaiah 40:31', 'Christian'),
    ('verse', ('Redeemed', None, 'I have redeemed thee, I have called thee by thy name; thou art mine.', 'Isaiah 43:1'), 'Redeemed Isaiah 43:1', 'Christian'),
    ('verse', ('Wonderfully', 'made', 'I will praise thee; for I am fearfully and wonderfully made.', 'Psalm 139:14'), 'Fearfully and Wonderfully Made Psalm 139', 'Christian'),
    ('verse', ('Mercy', 'new every morning', 'His compassions fail not. They are new every morning.', 'Lamentations 3:23'), 'New Every Morning Lamentations 3', 'Christian'),
    ('stack', [('Faith', 'script'), ('Over Fear', 'big')], 'Faith Over Fear', 'Christian'),
    ('stack', [('Pray More', 'big'), ('worry less', 'script')], 'Pray More Worry Less', 'Christian'),
    ('stack', [('Grateful', 'mid'), ('Thankful', 'mid'), ('Blessed', 'script')], 'Grateful Thankful Blessed', 'Christian'),
    ('minimal', ('Child of God', 'John 1:12'), 'Child of God', 'Christian'),
    ('badge', ('Saved by Grace', 'Amen', 'Ephesians 2:8'), 'Saved by Grace Badge', 'Christian'),
    ('groovy', ['Jesus', 'Saves'], 'Jesus Saves Retro', 'Christian'),
    # --- Cats ---
    ('stack', [('Cat', 'script'), ('Mom', 'big'), ('Est. 2026', 'small')], 'Cat Mom', 'Cat Lover'),
    ('stack', [('Cat', 'script'), ('Dad', 'big'), ('Est. 2026', 'small')], 'Cat Dad', 'Cat Lover'),
    ('groovy', ['Crazy', 'Cat Lady'], 'Crazy Cat Lady Retro', 'Cat Lover'),
    ('groovy', ['Stay', 'Pawsitive'], 'Stay Pawsitive', 'Cat Lover'),
    ('minimal', ('Nap Queen', 'Certified by my cat'), 'Nap Queen Cat', 'Cat Lover'),
    ('minimal', ('Introverted but willing|to discuss cats', None), 'Introverted But Willing to Discuss Cats', 'Cat Lover'),
    ('stack', [('I work hard', 'mid'), ('so my cat can have', 'small'), ('a better life', 'script')], 'I Work Hard So My Cat Can Have a Better Life', 'Cat Lover'),
    ('badge', ('Cats & Coffee', 'Meow', 'Club'), 'Cats and Coffee Club', 'Cat Lover'),
    ('groovy', ['Feline', 'Fine'], 'Feline Fine', 'Cat Lover'),
    ('groovy', ['Meowgical'], 'Meowgical', 'Cat Lover'),
    ('stack', [('Cat Hair', 'big'), ("don't care", 'script')], "Cat Hair Don't Care", 'Cat Lover'),
    ('badge', ('Rescue Cat Mom', 'Adopt', 'Love'), 'Rescue Cat Mom', 'Cat Lover'),
    ('sunset', ('Meow or Never', 'Cat Club', False), 'Meow or Never Retro Sunset', 'Cat Lover'),
    # --- Dogs ---
    ('stack', [('Dog', 'script'), ('Mom', 'big'), ('Est. 2026', 'small')], 'Dog Mom', 'Dog Lover'),
    ('stack', [('Dog', 'script'), ('Dad', 'big'), ('Est. 2026', 'small')], 'Dog Dad', 'Dog Lover'),
    ('stack', [('Life is better', 'mid'), ('with a dog', 'script')], 'Life Is Better With a Dog', 'Dog Lover'),
    ('badge', ('Good Boy Club', 'Woof', 'Members Only'), 'Good Boy Club', 'Dog Lover'),
    ('groovy', ['Pawsitive', 'Vibes'], 'Pawsitive Vibes', 'Dog Lover'),
    ('sunset', ('Walks & Wags', 'Dog Life', True), 'Walks and Wags Retro Sunset', 'Dog Lover'),
    ('stack', [('Bark less', 'big'), ('wag more', 'script')], 'Bark Less Wag More', 'Dog Lover'),
    ('stack', [('Rescue', 'big'), ('mom', 'script'), ('Adopt don\'t shop', 'small')], 'Rescue Mom', 'Dog Lover'),
    ('stack', [('Dog Hair', 'big'), ("don't care", 'script')], "Dog Hair Don't Care", 'Dog Lover'),
    # --- Coffee ---
    ('stack', [('But first', 'script'), ('Coffee', 'big')], 'But First Coffee', 'Coffee'),
    ('badge', ('Powered by Coffee', '100%', 'Caffeinated'), 'Powered by Coffee', 'Coffee'),
    ('stack', [('Coffee', 'big'), ('& kindness', 'script')], 'Coffee and Kindness', 'Coffee'),
    ('groovy', ['Espresso', 'Yourself'], 'Espresso Yourself', 'Coffee'),
    ('minimal', ('Iced Coffee Season', 'All year round'), 'Iced Coffee Season', 'Coffee'),
    ('stack', [('Caffeine', 'big'), ('queen', 'script')], 'Caffeine Queen', 'Coffee'),
    ('stack', [('Running on', 'small'), ('Caffeine', 'big'), ('& chaos', 'script')], 'Running on Caffeine and Chaos', 'Coffee'),
    # --- Outdoors ---
    ('sunset', ('Adventure Awaits', 'Explore more', True), 'Adventure Awaits Mountain Sunset', 'Outdoors'),
    ('sunset', ('The Mountains Are Calling', 'And I must go', True), 'The Mountains Are Calling', 'Outdoors'),
    ('badge', ('Take a Hike', 'Hike', 'Trail Club'), 'Take a Hike Trail Club', 'Outdoors'),
    ('groovy', ['Happy', 'Camper'], 'Happy Camper Retro', 'Outdoors'),
    ('badge', ('Go Outside', 'Explore', 'Est. 2026'), 'Go Outside Explore Badge', 'Outdoors'),
    ('sunset', ('Salt Water Heals Everything', 'Ocean therapy', False), 'Salt Water Heals Everything', 'Beach'),
    ('groovy', ['Beach', 'Please'], 'Beach Please', 'Beach'),
    ('badge', ('Lake Life', 'Lake', 'Sun & Water'), 'Lake Life Badge', 'Outdoors'),
    ('stack', [('Wanderlust', 'script'), ('Explore the world', 'small')], 'Wanderlust', 'Outdoors'),
    ('stack', [('Stay', 'big'), ('wild', 'script')], 'Stay Wild', 'Outdoors'),
    ('sunset', ('Sunset Chaser', 'Golden hour club', False), 'Sunset Chaser', 'Beach'),
    ('sunset', ('Ocean Lover', 'Sea you soon', False), 'Ocean Lover Retro Sunset', 'Beach'),
    ('groovy', ['Sea You', 'Soon'], 'Sea You Soon', 'Beach'),
    ('sunset', ('Ride the Wave', 'Surf club', False), 'Ride the Wave Surf', 'Beach'),
    ('badge', ('Camp Vibes', 'Camp', 'Sleep under stars'), 'Camp Vibes Badge', 'Outdoors'),
    ('badge', ('Summit Seeker', 'Peak', 'Mountain Club'), 'Summit Seeker', 'Outdoors'),
    ('badge', ('Forest Bathing Club', 'Breathe', 'Nature Heals'), 'Forest Bathing Club', 'Outdoors'),
    ('sunset', ('Lost in the Mountains', 'Found myself', True), 'Lost in the Mountains', 'Outdoors'),
    ('sunset', ('Desert Dreamer', 'Wild & free', True), 'Desert Dreamer', 'Outdoors'),
    # --- Retro / positive ---
    ('groovy', ['Good Vibes', 'Only'], 'Good Vibes Only', 'Retro'),
    ('groovy', ['Stay', 'Groovy'], 'Stay Groovy', 'Retro'),
    ('groovy', ['Peace', 'Love', 'Sunshine'], 'Peace Love Sunshine', 'Retro'),
    ('sunset', ('Hello Sunshine', 'Good days ahead', False), 'Hello Sunshine Retro Sunset', 'Retro'),
    ('stack', [('Be', 'script'), ('Kind', 'big')], 'Be Kind', 'Positive'),
    ('groovy', ['Choose', 'Kindness'], 'Choose Kindness', 'Positive'),
    ('stack', [('Positive mind', 'mid'), ('positive life', 'script')], 'Positive Mind Positive Life', 'Positive'),
    ('sunset', ('Retro Soul', 'Born in the wrong decade', False), 'Retro Soul', 'Retro'),
    ('stack', [('Bloom', 'script'), ('where you are', 'mid'), ('planted', 'script')], 'Bloom Where You Are Planted', 'Positive'),
    ('groovy', ['Kindness', 'Is Cool'], 'Kindness Is Cool', 'Positive'),
    ('groovy', ['Radiate', 'Positivity'], 'Radiate Positivity', 'Positive'),
    ('groovy', ['Spread', 'Love'], 'Spread Love', 'Positive'),
    ('sunset', ('Sunshine State of Mind', None, False), 'Sunshine State of Mind', 'Retro'),
    ('minimal', ('Find joy in the|little things', None), 'Find Joy in the Little Things', 'Positive'),
    ('stack', [('Do more of', 'small'), ('what makes you', 'mid'), ('happy', 'script')], 'Do More of What Makes You Happy', 'Positive'),
    ('groovy', ['Main Character', 'Energy'], 'Main Character Energy', 'Retro'),
    # --- Family ---
    ('stack', [('Mama', 'big'), ('Est. 2026', 'small')], 'Mama Est. 2026', 'Family'),
    ('sunset', ('Mama Bear', 'Protect & love', True), 'Mama Bear Retro Sunset', 'Family'),
    ('sunset', ('Papa Bear', 'Strong & proud', True), 'Papa Bear Retro Sunset', 'Family'),
    ('badge', ('Girl Dad', 'Proud', 'Est. 2026'), 'Girl Dad Badge', 'Family'),
    ('stack', [('Boy', 'script'), ('Mom', 'big')], 'Boy Mom', 'Family'),
    ('badge', ('Best Dad Ever', '#1', 'Since forever'), 'Best Dad Ever', 'Family'),
    ('stack', [('Blessed', 'script'), ('Mama', 'big')], 'Blessed Mama', 'Family'),
    ('groovy', ['Aunt', 'Life'], 'Aunt Life', 'Family'),
    ('stack', [('Grandma', 'script'), ('Life', 'big')], 'Grandma Life', 'Family'),
    ('groovy', ['Mom', 'Life'], 'Mom Life Retro', 'Family'),
    ('minimal', ('Dad Jokes|Loading...', 'Please wait'), 'Dad Jokes Loading', 'Family'),
    ('badge', ('Reel Cool Dad', 'Fish', 'Since 2026'), 'Reel Cool Dad', 'Family'),
    ('stack', [('Wife', 'mid'), ('Mom', 'mid'), ('Boss', 'script')], 'Wife Mom Boss', 'Family'),
    ('badge', ('Nana Est. 2026', 'Nana', 'Loved'), 'Nana Est. 2026', 'Family'),
    # --- Jobs ---
    ('stack', [('Teacher', 'script'), ('Life', 'big')], 'Teacher Life', 'Teacher'),
    ('stack', [('Coffee', 'mid'), ('Teach', 'mid'), ('Repeat', 'script')], 'Coffee Teach Repeat', 'Teacher'),
    ('stack', [('Nurse', 'script'), ('Life', 'big')], 'Nurse Life', 'Nurse'),
    ('groovy', ['Teach', 'Love', 'Inspire'], 'Teach Love Inspire', 'Teacher'),
    ('badge', ('Nurse Mode On', 'RN', 'Caring 24/7'), 'Nurse Mode On', 'Nurse'),
    # --- Funny / lifestyle ---
    ('minimal', ('Professional|Overthinker', 'Since birth'), 'Professional Overthinker', 'Funny'),
    ('minimal', ('Social Battery|Low', 'Please recharge later'), 'Social Battery Low', 'Funny'),
    ('sunset', ('Out of Office', 'Gone fishing', False), 'Out of Office Retro', 'Funny'),
    ('badge', ('Weekend Mode', 'On', 'Do not disturb'), 'Weekend Mode', 'Funny'),
    ('badge', ('Nap Champion', 'Zzz', 'Undefeated'), 'Nap Champion', 'Funny'),
    ('groovy', ['Plant', 'Lady'], 'Plant Lady', 'Plants'),
    ('stack', [('Plant', 'script'), ('Mom', 'big')], 'Plant Mom', 'Plants'),
    ('stack', [('Book', 'script'), ('Lover', 'big')], 'Book Lover', 'Books'),
    ('minimal', ('Just one more|chapter', None), 'Just One More Chapter', 'Books'),
    ('badge', ('Bookworm Club', 'Read', 'Est. 2026'), 'Bookworm Club', 'Books'),
    ('badge', ('Introvert Club', 'Shh', 'We meet never'), 'Introvert Club', 'Funny'),
    ('stack', [('Eat', 'mid'), ('Sleep', 'mid'), ('Game', 'mid'), ('Repeat', 'script')], 'Eat Sleep Game Repeat', 'Gaming'),
    ('badge', ('Gamer Mode', 'Play', 'Level up'), 'Gamer Mode', 'Gaming'),
    ('sunset', ('Mentally on Vacation', None, False), 'Mentally on Vacation', 'Funny'),
    ('minimal', ('Not Today', None), 'Not Today', 'Funny'),
    ('minimal', ('Do Not Disturb', 'Recharging'), 'Do Not Disturb', 'Funny'),
    ('groovy', ['Snack', 'Time'], 'Snack Time', 'Funny'),
    ('stack', [('Pizza', 'big'), ('is my love language', 'small')], 'Pizza Is My Love Language', 'Funny'),
    ('stack', [('Tacos', 'big'), ('& good vibes', 'script')], 'Tacos and Good Vibes', 'Funny'),
    # --- Motivation ---
    ('sunset', ('Dream Big', 'Work hard', False), 'Dream Big Retro Sunset', 'Motivation'),
    ('stack', [('Be', 'script'), ('Brave', 'big')], 'Be Brave', 'Motivation'),
    ('groovy', ['You Got', 'This'], 'You Got This', 'Motivation'),
    ('minimal', ('One day at a time', None), 'One Day at a Time', 'Motivation'),
    ('stack', [('Keep', 'script'), ('Going', 'big')], 'Keep Going', 'Motivation'),
    ('badge', ('Stay Strong', 'Strong', 'Never give up'), 'Stay Strong Badge', 'Motivation'),
    ('stack', [('Make today', 'mid'), ('count', 'script')], 'Make Today Count', 'Motivation'),
    ('groovy', ['Choose', 'Joy'], 'Choose Joy', 'Motivation'),
    ('badge', ('Self Love Club', 'Love', 'Members'), 'Self Love Club', 'Motivation'),
    ('stack', [('Mental health', 'mid'), ('matters', 'script')], 'Mental Health Matters', 'Motivation'),
    ('minimal', ('You are enough', None), 'You Are Enough', 'Motivation'),
    ('minimal', ('Progress|not perfection', None), 'Progress Not Perfection', 'Motivation'),
    ('minimal', ('Good things|take time', None), 'Good Things Take Time', 'Motivation'),
    ('stack', [('Stay', 'script'), ('Humble', 'big')], 'Stay Humble', 'Motivation'),
    ('sunset', ('Rise and Grind', 'Every day', True), 'Rise and Grind', 'Motivation'),
    # --- Music ---
    ('stack', [('Music', 'big'), ('is my therapy', 'script')], 'Music Is My Therapy', 'Music'),
    ('groovy', ['Good Music', 'Good Vibes'], 'Good Music Good Vibes', 'Music'),
    ('badge', ('Vinyl Junkie', '33 RPM', 'Spin it'), 'Vinyl Junkie', 'Music'),
    ('stack', [('Rock & Roll', 'big'), ('forever', 'script')], 'Rock and Roll Forever', 'Music'),
    ('sunset', ('Festival Season', 'Live music', False), 'Festival Season', 'Music'),
    ('badge', ('Acoustic Soul', 'Folk', 'Unplugged'), 'Acoustic Soul Folk', 'Music'),
    # --- Seasonal ---
    ('groovy', ['Fall', 'Vibes'], 'Fall Vibes', 'Fall'),
    ('stack', [('Hello', 'script'), ('Pumpkin', 'big')], 'Hello Pumpkin', 'Fall'),
    ('stack', [('Pumpkin Spice', 'mid'), ('season', 'script')], 'Pumpkin Spice Season', 'Fall'),
    ('groovy', ['Sweater', 'Weather'], 'Sweater Weather', 'Fall'),
    ('minimal', ('Cozy Season', 'Blankets & books'), 'Cozy Season', 'Fall'),
    ('groovy', ['Spooky', 'Season'], 'Spooky Season Retro', 'Halloween'),
    ('badge', ('Boo Crew', 'Boo', 'Halloween'), 'Boo Crew Halloween', 'Halloween'),
    ('stack', [('Merry', 'script'), ('& Bright', 'big')], 'Merry and Bright', 'Christmas'),
    ('groovy', ['Holly Jolly', 'Vibes'], 'Holly Jolly Vibes', 'Christmas'),
    ('stack', [('Snow', 'big'), ('much fun', 'script')], 'Snow Much Fun', 'Christmas'),
    ('sunset', ('Summer Vibes', 'Sun & sand', False), 'Summer Vibes Retro Sunset', 'Summer'),
    ('stack', [('Hello', 'script'), ('Spring', 'big')], 'Hello Spring', 'Spring'),
    ('stack', [('Thankful', 'big'), ('& blessed', 'script')], 'Thankful and Blessed', 'Fall'),
    ('groovy', ["Happy Fall", "Y'all"], "Happy Fall Y'all", 'Fall'),
    ('badge', ('Christmas Crew', 'Ho Ho', 'Family'), 'Christmas Crew', 'Christmas'),
    ('stack', [('Let it', 'script'), ('Snow', 'big')], 'Let It Snow', 'Christmas'),
    # --- Sports & hobbies ---
    ('badge', ('Game Day', 'Go Team', 'Every weekend'), 'Game Day', 'Sports'),
    ('stack', [('Baseball', 'script'), ('Mom', 'big')], 'Baseball Mom', 'Sports'),
    ('stack', [('Soccer', 'script'), ('Mom', 'big')], 'Soccer Mom', 'Sports'),
    ('sunset', ('Football Season', 'Friday nights', False), 'Football Season', 'Sports'),
    ('badge', ('Gym Rat', 'Lift', 'No days off'), 'Gym Rat', 'Fitness'),
    ('groovy', ['Yoga', 'Vibes'], 'Yoga Vibes', 'Fitness'),
    ('badge', ('Pickleball Club', 'Dink', 'Est. 2026'), 'Pickleball Club', 'Sports'),
    ('badge', ('Golf & Chill', 'Fore', 'Weekend club'), 'Golf and Chill', 'Sports'),
    ('sunset', ('Fishing Is My Therapy', 'Reel life', True), 'Fishing Is My Therapy', 'Fishing'),
    ('badge', ('Born to Fish', 'Fish', 'Forced to work'), 'Born to Fish', 'Fishing'),
    ('stack', [('Lift heavy', 'big'), ('pray often', 'script')], 'Lift Heavy Pray Often', 'Fitness'),
    ('sunset', ('Ride or Die', 'Moto club', True), 'Ride or Die Moto', 'Motorcycle'),
    ('badge', ('Garden Club', 'Grow', 'Dirt therapy'), 'Garden Club', 'Plants'),
    ('stack', [('Horse', 'script'), ('Girl', 'big')], 'Horse Girl', 'Horses'),
    ('groovy', ['Bee', 'Kind'], 'Bee Kind', 'Positive'),
    ('stack', [('Chicken', 'script'), ('Lady', 'big')], 'Chicken Lady', 'Farm'),
    ('badge', ('Farm Life', 'Farm', 'Fresh eggs'), 'Farm Life', 'Farm'),
    ('stack', [('Country', 'script'), ('Roots', 'big')], 'Country Roots', 'Farm'),
    ('sunset', ('Road Trip', 'Windows down', True), 'Road Trip Retro', 'Travel'),
    ('badge', ('Passport Ready', 'Travel', 'See the world'), 'Passport Ready', 'Travel'),
]
