import productData from "./products.json";
import apparelData from "./apparel.json";

export interface Product {
  id: string;
  name: string;
  price: string;
  category: string;
  img: string;
  description: string;
  features: string[];
}

// Print-on-demand apparel (generated by scripts/pod) listed first, then the wholesale catalog
export const allProducts: Product[] = [...(apparelData as Product[]), ...(productData as Product[])];
