import productData from "./products.json";
import apparelData from "./apparel.json";

export interface Product {
  id: string;
  name: string;
  price: string;
  category: string;
  img: string;
  description: string;
  features: string[];
}

// Department filter that groups every apparel category
export const APPAREL = "Apparel";

const APPAREL_ORDER = ["T-Shirts", "Hoodies", "Sweatshirts", "Long Sleeves", "Tank Tops", "Kids & Youth"];

const apparel = apparelData as Product[];

export const apparelCategories: string[] = APPAREL_ORDER.filter((c) => apparel.some((p) => p.category === c));

export const isApparelCategory = (category: string) => category === APPAREL || apparelCategories.includes(category);

// Print-on-demand apparel (generated by scripts/pod) listed first, then the wholesale catalog
export const allProducts: Product[] = [...apparel, ...(productData as Product[])];
